### ISSUE TITLE
termux android 

### ISSUE THREAD

**Issue by molafir** [SoftCreatR/warp-up#2]
**Attach the following commands output**

- [ ] lsb_release -a :

**Describe the bug**
Iterations : 1                                          Interval   : 20
                                                         Log File   : warp-up.log
 Travis     : no                                        
 ##################
 Generation Process
 ##################
                                                        warp-up.sh: line 359: shasum: command not found
$

**Comment by SoftCreatR** [comment]
I guess, that this isn't the only issue when ran under Termux. But I'll see, what I can do.

**Comment by SoftCreatR** [comment]
Fixed via dfeeb74263c6a4719294dac2a20fc26887a4d4ff, however, it may still fail on Termux.

**Comment by SoftCreatR** [comment]
Just a quick heads up: I was able to run it under Termux, but it requires some additional work because it doesn't work in bare Termux.

In order to make it work in Termux, you have to install Ubuntu inside of it:

1. Update termux: `apt-get update && apt-get upgrade -y`
2. Install wget: `apt-get install wget -y`
3. Install proot: `apt-get install proot -y`
4. Install git: `apt-get install git -y`
5. Go to HOME folder: `cd ~`
6. Download script: `git clone https://github.com/MFDGaming/ubuntu-in-termux.git`
7. Go to script folder: `cd ubuntu-in-termux`
8. Give execution permission: `chmod +x ubuntu.sh`
9. Run the script: `./ubuntu.sh -y`
10. Now just start ubuntu: `./startubuntu.sh`

When done, you need to perform 3 more steps:

1. Run `apt update && apt upgrade -y`
2. Install wget: `apt install curl -y`
3. Download/Install Warp-Up as described in the readme

That's it:

![Screenshot_20210403-230645_Termux](https://user-images.githubusercontent.com/81188/113491679-d905a180-94d2-11eb-8963-1f0876684456.jpg)

**Comment by molafir** [comment]
> Just a quick heads up: I was able to run it under Termux, but it requires some additional work because it doesn't work in bare Termux.
> 
> In order to make it work in Termux, you have to install Ubuntu inside of it:
> 
> 1. Update termux: `apt-get update && apt-get upgrade -y`
> 2. Install wget: `apt-get install wget -y`
> 3. Install proot: `apt-get install proot -y`
> 4. Install git: `apt-get install git -y`
> 5. Go to HOME folder: `cd ~`
> 6. Download script: `git clone https://github.com/MFDGaming/ubuntu-in-termux.git`
> 7. Go to script folder: `cd ubuntu-in-termux`
> 8. Give execution permission: `chmod +x ubuntu.sh`
> 9. Run the script: `./ubuntu.sh -y`
> 10. Now just start ubuntu: `./startubuntu.sh`
> 
> When done, you need to perform 3 more steps:
> 
> 1. Run `apt update && apt upgrade -y`
> 2. Install wget: `apt install curl -y`
> 3. Download/Install Warp-Up as described in the readme
> 
> That's it:
> 
> ![Screenshot_20210403-230645_Termux](https://user-images.githubusercontent.com/81188/113491679-d905a180-94d2-11eb-8963-1f0876684456.jpg)

Nice working 
![Screenshot_20210404-100403~2](https://user-images.githubusercontent.com/12770700/113499935-4810e380-952f-11eb-9cbb-c64be7b5596b.jpg)
